### ISSUE TITLE
database 

### ISSUE THREAD

**Issue by abuwalid14** [AhnafSayed/E-Tourism-Project#1]
please do u have the .sql file for this project ?

**Comment by AhnafSayed** [comment]
Yes.
[E-Tourism.zip](https://github.com/AhnafSayed/E-Tourism-Project/files/8398411/E-Tourism.zip)

**Comment by abuwalid14** [comment]
jazaka allah kheir, baraka allahu fik and ramadan mubarak

**Comment by AhnafSayed** [comment]
Ramadan Mubarak!
